INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('803 Glacier Hill Alley', null, 'Lubbock', 'TX', '79491', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('86 Prentice Hill', null, 'Saint Paul', 'MN', '55188', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('7 Hovde Lane', null, 'Detroit', 'MI', '48232', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('624 Miller Way', null, 'Dallas', 'TX', '75260', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('9 Bunting Point', null, 'Indianapolis', 'IN', '46216', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('4688 Erie Trail', null, 'Montgomery', 'AL', '36125', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('7 Vahlen Center', null, 'Norcross', 'GA', '30092', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('9 Northwestern Lane', null, 'Huntington', 'WV', '25721', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('26261 Delaware Trail', null, 'El Paso', 'TX', '79945', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('00 Esker Point', null, 'Lake Worth', 'FL', '33462', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('8 Bobwhite Drive', null, 'Chicago', 'IL', '60636', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('006 Carberry Trail', null, 'Albany', 'GA', '31704', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('14 Florence Road', null, 'Washington', 'DC', '20260', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('9040 Mesta Hill', '213', 'Worcester', 'MA', '01605', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('3931 Bobwhite Road', null, 'Grand Rapids', 'MI', '49505', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('8053 Pennsylvania Parkway', '13', 'San Diego', 'CA', '92145', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('3 Comanche Center', null, 'Reno', 'NV', '89595', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('8776 Bowman Court', '3982', 'Denver', 'CO', '80204', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('79 2nd Pass', null, 'Minneapolis', 'MN', '55407', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('30584 Roxbury Parkway', null, 'Honolulu', 'HI', '96840', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('450 Elmside Alley', null, 'Lexington', 'KY', '40515', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('6 Loomis Plaza', null, 'Lubbock', 'TX', '79452', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('59 Barby Point', '43227', 'Washington', 'DC', '20046', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('5 Everett Crossing', null, 'Des Moines', 'IA', '50305', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('75333 Welch Terrace', null, 'San Francisco', 'CA', '94142', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('5023 Mallard Alley', null, 'Houston', 'TX', '77060', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('424 Myrtle Circle', null, 'Colorado Springs', 'CO', '80945', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('30 Blue Bill Park Pass', '63', 'Amarillo', 'TX', '79159', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('442 Rockefeller Alley', null, 'San Bernardino', 'CA', '92424', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('523 Maple Wood Place', null, 'Des Moines', 'IA', '50393', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('9464 Corry Circle', null, 'San Antonio', 'TX', '78210', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('407 Upham Hill', null, 'Hartford', 'CT', '06152', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('5213 Ruskin Road', null, 'Irvine', 'CA', '92612', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('4 Sunfield Circle', null, 'El Paso', 'TX', '88553', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('0334 Dahle Park', '39', 'Los Angeles', 'CA', '90035', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('67 Wayridge Pass', null, 'New York City', 'NY', '10079', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('6 Waubesa Street', null, 'Santa Fe', 'NM', '87592', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('427 Schmedeman Pass', '381', 'Lexington', 'KY', '40546', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('1307 West Point', null, 'Louisville', 'KY', '40205', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('77 5th Trail', null, 'Toledo', 'OH', '43635', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('03139 Michigan Lane', null, 'Toledo', 'OH', '43635', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('71 Elgar Drive', null, 'Sacramento', 'CA', '94297', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('924 Arizona Road', null, 'Reston', 'VA', '22096', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('6685 Stephen Street', null, 'San Francisco', 'CA', '94177', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('694 Golf Course Court', null, 'New Orleans', 'LA', '70160', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('7257 Golf Parkway', null, 'San Antonio', 'TX', '78291', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('288 Arrowood Center', null, 'Salt Lake City', 'UT', '84110', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('56974 Hoepker Lane', '780', 'Abilene', 'TX', '79699', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('18987 Schiller Parkway', null, 'Pittsburgh', 'PA', '15215', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('9844 Toban Road', null, 'Huntington Beach', 'CA', '92648', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('03 Colorado Court', '06151', 'Rochester', 'NY', '14683', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('3 Ruskin Court', null, 'Spokane', 'WA', '99215', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('0122 Ryan Trail', null, 'Santa Monica', 'CA', '90410', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('6501 Ilene Junction', '40219', 'Shawnee Mission', 'KS', '66215', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('50785 American Ash Avenue', null, 'Lincoln', 'NE', '68583', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('92 Hollow Ridge Crossing', null, 'Madison', 'WI', '53710', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('03 Marquette Crossing', null, 'Miami', 'FL', '33153', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('62126 Dixon Plaza', '989', 'Austin', 'TX', '78732', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('0901 Raven Park', null, 'Dallas', 'TX', '75342', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('69 3rd Park', null, 'Glendale', 'CA', '91205', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('259 2nd Drive', null, 'Fullerton', 'CA', '92835', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('5 Evergreen Drive', null, 'Omaha', 'NE', '68110', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('6 Northfield Trail', null, 'Santa Fe', 'NM', '87505', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('2444 Waubesa Circle', null, 'Frederick', 'MD', '21705', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('9 International Court', null, 'Sacramento', 'CA', '95818', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('213 Grover Center', null, 'Tulsa', 'OK', '74126', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('810 Haas Plaza', null, 'College Station', 'TX', '77844', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('89055 Valley Edge Junction', null, 'Pittsburgh', 'PA', '15261', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('45 Messerschmidt Place', null, 'Great Neck', 'NY', '11024', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('68 Commercial Street', null, 'Dallas', 'TX', '75397', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('2083 Dawn Court', null, 'Spartanburg', 'SC', '29305', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('5251 Red Cloud Terrace', null, 'Savannah', 'GA', '31410', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('39527 Almo Junction', null, 'Bakersfield', 'CA', '93305', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('34 Pearson Center', null, 'Charlotte', 'NC', '28247', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('767 Thackeray Place', null, 'Milwaukee', 'WI', '53234', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('682 Katie Street', '988', 'Ocala', 'FL', '34479', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('9060 Claremont Pass', null, 'Minneapolis', 'MN', '55417', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('87 Ruskin Drive', null, 'Philadelphia', 'PA', '19178', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('8 Hanson Hill', null, 'Atlanta', 'GA', '30340', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('81 Merrick Terrace', null, 'New Haven', 'CT', '06510', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('817 Mayer Road', null, 'Evansville', 'IN', '47719', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('3234 Hayes Trail', null, 'Galveston', 'TX', '77554', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('196 Artisan Drive', '76198', 'Indianapolis', 'IN', '46202', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('6 Sunnyside Lane', null, 'Tallahassee', 'FL', '32399', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('965 3rd Parkway', null, 'Jacksonville', 'FL', '32277', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('80059 Bultman Court', null, 'Dearborn', 'MI', '48126', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('36 Ridge Oak Court', '13', 'Panama City', 'FL', '32405', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('719 Forest Way', null, 'San Bernardino', 'CA', '92424', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('85 Grim Trail', null, 'Midland', 'MI', '48670', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('363 Karstens Plaza', null, 'Springfield', 'MA', '01105', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('1 Algoma Lane', null, 'Saint Louis', 'MO', '63126', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('8 Pankratz Circle', null, 'Albuquerque', 'NM', '87190', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('94 Old Gate Hill', null, 'Harrisburg', 'PA', '17105', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('6783 Transport Park', null, 'Sioux Falls', 'SD', '57188', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('4698 Warbler Street', null, 'Louisville', 'KY', '40210', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('6 Fordem Court', null, 'Brooklyn', 'NY', '11236', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('2602 Grim Way', null, 'Reno', 'NV', '89510', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('6234 Glacier Hill Road', null, 'Fort Smith', 'AR', '72916', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('212 Bowman Park', '09560', 'Sacramento', 'CA', '95838', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('1 International Avenue', null, 'New Haven', 'CT', '06505', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('0837 Merrick Plaza', null, 'Waterbury', 'CT', '06721', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('69796 Boyd Avenue', null, 'San Jose', 'CA', '95113', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('9 Stephen Place', null, 'Atlanta', 'GA', '30328', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('9 Crescent Oaks Center', null, 'New York City', 'NY', '10131', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('8121 Vermont Road', null, 'Pueblo', 'CO', '81015', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('1 Rieder Alley', null, 'Tampa', 'FL', '33605', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('56 Columbus Alley', null, 'Allentown', 'PA', '18105', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('8420 Hauk Hill', null, 'Houston', 'TX', '77050', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('0 South Hill', null, 'Honolulu', 'HI', '96820', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('48 Magdeline Avenue', null, 'San Antonio', 'TX', '78215', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('71 Susan Circle', null, 'Naperville', 'IL', '60567', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('49 Sheridan Alley', null, 'Huntsville', 'AL', '35805', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('74 Esch Junction', '81', 'Miami', 'FL', '33142', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('30 Dottie Alley', null, 'Amarillo', 'TX', '79182', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('39 Grasskamp Street', null, 'Charleston', 'WV', '25336', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('88357 Elgar Hill', null, 'Boulder', 'CO', '80310', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('916 Columbus Road', null, 'Colorado Springs', 'CO', '80935', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('9150 Bay Point', '14', 'Sacramento', 'CA', '95828', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('44309 Crest Line Road', null, 'Montgomery', 'AL', '36114', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('96195 Randy Lane', '3', 'Tulsa', 'OK', '74116', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('9 Hazelcrest Alley', null, 'Washington', 'DC', '20057', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('1 Service Avenue', null, 'Washington', 'DC', '20557', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('35 Anderson Circle', null, 'Denver', 'CO', '80291', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('365 Vidon Avenue', null, 'Silver Spring', 'MD', '20904', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('6 Sutherland Circle', null, 'Arlington', 'VA', '22212', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('475 Schlimgen Point', null, 'Odessa', 'TX', '79769', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('297 Bunting Circle', '4', 'Hialeah', 'FL', '33018', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('729 Sunnyside Road', null, 'Washington', 'DC', '20414', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('4 Thackeray Street', '71', 'Atlanta', 'GA', '30358', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('313 Oxford Court', null, 'Shreveport', 'LA', '71137', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('71695 Elka Park', null, 'Boca Raton', 'FL', '33487', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('394 Vernon Hill', null, 'Round Rock', 'TX', '78682', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('1 Farragut Park', null, 'Little Rock', 'AR', '72215', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('1741 Browning Place', null, 'Detroit', 'MI', '48232', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('33 Cherokee Alley', null, 'Cincinnati', 'OH', '45264', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('5715 Onsgard Plaza', null, 'Mount Vernon', 'NY', '10557', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('92 Lukken Court', null, 'Ocala', 'FL', '34479', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('2008 Johnson Court', null, 'Buffalo', 'NY', '14215', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('7 Kingsford Drive', null, 'Arlington', 'VA', '22217', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('82 North Plaza', null, 'Winston Salem', 'NC', '27110', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('4987 Spohn Pass', null, 'San Diego', 'CA', '92105', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('757 Anderson Trail', null, 'Sioux Falls', 'SD', '57188', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('49526 Lillian Pass', null, 'Portland', 'OR', '97201', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('76 Twin Pines Street', null, 'San Antonio', 'TX', '78278', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('6 Hanson Lane', null, 'Naples', 'FL', '34108', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('986 Portage Court', null, 'Houston', 'TX', '77293', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('51140 Cambridge Way', null, 'Santa Barbara', 'CA', '93150', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('52431 Comanche Lane', null, 'Los Angeles', 'CA', '90025', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('04619 Manitowish Crossing', null, 'Evansville', 'IN', '47712', 'US');
INSERT INTO `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) VALUES ('447 Corben Way', null, 'Jersey City', 'NJ', '07305', 'US');