insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('803 Glacier Hill Alley', null, 'Lubbock', 'TX', '79491', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('86 Prentice Hill', null, 'Saint Paul', 'MN', '55188', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('7 Hovde Lane', null, 'Detroit', 'MI', '48232', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('624 Miller Way', null, 'Dallas', 'TX', '75260', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9 Bunting Point', null, 'Indianapolis', 'IN', '46216', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('4688 Erie Trail', null, 'Montgomery', 'AL', '36125', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('7 Vahlen Center', null, 'Norcross', 'GA', '30092', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9 Northwestern Lane', null, 'Huntington', 'WV', '25721', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('26261 Delaware Trail', null, 'El Paso', 'TX', '79945', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('00 Esker Point', null, 'Lake Worth', 'FL', '33462', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('8 Bobwhite Drive', null, 'Chicago', 'IL', '60636', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('006 Carberry Trail', null, 'Albany', 'GA', '31704', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('14 Florence Road', null, 'Washington', 'DC', '20260', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9040 Mesta Hill', '213', 'Worcester', 'MA', '01605', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('3931 Bobwhite Road', null, 'Grand Rapids', 'MI', '49505', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('8053 Pennsylvania Parkway', '13', 'San Diego', 'CA', '92145', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('3 Comanche Center', null, 'Reno', 'NV', '89595', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('8776 Bowman Court', '3982', 'Denver', 'CO', '80204', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('79 2nd Pass', null, 'Minneapolis', 'MN', '55407', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('30584 Roxbury Parkway', null, 'Honolulu', 'HI', '96840', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('450 Elmside Alley', null, 'Lexington', 'KY', '40515', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6 Loomis Plaza', null, 'Lubbock', 'TX', '79452', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('59 Barby Point', '43227', 'Washington', 'DC', '20046', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('5 Everett Crossing', null, 'Des Moines', 'IA', '50305', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('75333 Welch Terrace', null, 'San Francisco', 'CA', '94142', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('5023 Mallard Alley', null, 'Houston', 'TX', '77060', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('424 Myrtle Circle', null, 'Colorado Springs', 'CO', '80945', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('30 Blue Bill Park Pass', '63', 'Amarillo', 'TX', '79159', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('442 Rockefeller Alley', null, 'San Bernardino', 'CA', '92424', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('523 Maple Wood Place', null, 'Des Moines', 'IA', '50393', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9464 Corry Circle', null, 'San Antonio', 'TX', '78210', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('407 Upham Hill', null, 'Hartford', 'CT', '06152', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('5213 Ruskin Road', null, 'Irvine', 'CA', '92612', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('4 Sunfield Circle', null, 'El Paso', 'TX', '88553', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('0334 Dahle Park', '39', 'Los Angeles', 'CA', '90035', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('67 Wayridge Pass', null, 'New York City', 'NY', '10079', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6 Waubesa Street', null, 'Santa Fe', 'NM', '87592', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('427 Schmedeman Pass', '381', 'Lexington', 'KY', '40546', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('1307 West Point', null, 'Louisville', 'KY', '40205', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('77 5th Trail', null, 'Toledo', 'OH', '43635', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('03139 Michigan Lane', null, 'Toledo', 'OH', '43635', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('71 Elgar Drive', null, 'Sacramento', 'CA', '94297', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('924 Arizona Road', null, 'Reston', 'VA', '22096', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6685 Stephen Street', null, 'San Francisco', 'CA', '94177', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('694 Golf Course Court', null, 'New Orleans', 'LA', '70160', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('7257 Golf Parkway', null, 'San Antonio', 'TX', '78291', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('288 Arrowood Center', null, 'Salt Lake City', 'UT', '84110', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('56974 Hoepker Lane', '780', 'Abilene', 'TX', '79699', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('18987 Schiller Parkway', null, 'Pittsburgh', 'PA', '15215', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9844 Toban Road', null, 'Huntington Beach', 'CA', '92648', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('03 Colorado Court', '06151', 'Rochester', 'NY', '14683', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('3 Ruskin Court', null, 'Spokane', 'WA', '99215', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('0122 Ryan Trail', null, 'Santa Monica', 'CA', '90410', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6501 Ilene Junction', '40219', 'Shawnee Mission', 'KS', '66215', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('50785 American Ash Avenue', null, 'Lincoln', 'NE', '68583', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('92 Hollow Ridge Crossing', null, 'Madison', 'WI', '53710', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('03 Marquette Crossing', null, 'Miami', 'FL', '33153', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('62126 Dixon Plaza', '989', 'Austin', 'TX', '78732', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('0901 Raven Park', null, 'Dallas', 'TX', '75342', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('69 3rd Park', null, 'Glendale', 'CA', '91205', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('259 2nd Drive', null, 'Fullerton', 'CA', '92835', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('5 Evergreen Drive', null, 'Omaha', 'NE', '68110', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6 Northfield Trail', null, 'Santa Fe', 'NM', '87505', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('2444 Waubesa Circle', null, 'Frederick', 'MD', '21705', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9 International Court', null, 'Sacramento', 'CA', '95818', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('213 Grover Center', null, 'Tulsa', 'OK', '74126', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('810 Haas Plaza', null, 'College Station', 'TX', '77844', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('89055 Valley Edge Junction', null, 'Pittsburgh', 'PA', '15261', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('45 Messerschmidt Place', null, 'Great Neck', 'NY', '11024', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('68 Commercial Street', null, 'Dallas', 'TX', '75397', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('2083 Dawn Court', null, 'Spartanburg', 'SC', '29305', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('5251 Red Cloud Terrace', null, 'Savannah', 'GA', '31410', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('39527 Almo Junction', null, 'Bakersfield', 'CA', '93305', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('34 Pearson Center', null, 'Charlotte', 'NC', '28247', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('767 Thackeray Place', null, 'Milwaukee', 'WI', '53234', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('682 Katie Street', '988', 'Ocala', 'FL', '34479', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9060 Claremont Pass', null, 'Minneapolis', 'MN', '55417', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('87 Ruskin Drive', null, 'Philadelphia', 'PA', '19178', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('8 Hanson Hill', null, 'Atlanta', 'GA', '30340', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('81 Merrick Terrace', null, 'New Haven', 'CT', '06510', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('817 Mayer Road', null, 'Evansville', 'IN', '47719', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('3234 Hayes Trail', null, 'Galveston', 'TX', '77554', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('196 Artisan Drive', '76198', 'Indianapolis', 'IN', '46202', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6 Sunnyside Lane', null, 'Tallahassee', 'FL', '32399', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('965 3rd Parkway', null, 'Jacksonville', 'FL', '32277', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('80059 Bultman Court', null, 'Dearborn', 'MI', '48126', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('36 Ridge Oak Court', '13', 'Panama City', 'FL', '32405', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('719 Forest Way', null, 'San Bernardino', 'CA', '92424', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('85 Grim Trail', null, 'Midland', 'MI', '48670', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('363 Karstens Plaza', null, 'Springfield', 'MA', '01105', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('1 Algoma Lane', null, 'Saint Louis', 'MO', '63126', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('8 Pankratz Circle', null, 'Albuquerque', 'NM', '87190', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('94 Old Gate Hill', null, 'Harrisburg', 'PA', '17105', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6783 Transport Park', null, 'Sioux Falls', 'SD', '57188', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('4698 Warbler Street', null, 'Louisville', 'KY', '40210', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6 Fordem Court', null, 'Brooklyn', 'NY', '11236', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('2602 Grim Way', null, 'Reno', 'NV', '89510', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6234 Glacier Hill Road', null, 'Fort Smith', 'AR', '72916', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('212 Bowman Park', '09560', 'Sacramento', 'CA', '95838', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('1 International Avenue', null, 'New Haven', 'CT', '06505', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('0837 Merrick Plaza', null, 'Waterbury', 'CT', '06721', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('69796 Boyd Avenue', null, 'San Jose', 'CA', '95113', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9 Stephen Place', null, 'Atlanta', 'GA', '30328', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9 Crescent Oaks Center', null, 'New York City', 'NY', '10131', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('8121 Vermont Road', null, 'Pueblo', 'CO', '81015', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('1 Rieder Alley', null, 'Tampa', 'FL', '33605', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('56 Columbus Alley', null, 'Allentown', 'PA', '18105', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('8420 Hauk Hill', null, 'Houston', 'TX', '77050', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('0 South Hill', null, 'Honolulu', 'HI', '96820', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('48 Magdeline Avenue', null, 'San Antonio', 'TX', '78215', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('71 Susan Circle', null, 'Naperville', 'IL', '60567', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('49 Sheridan Alley', null, 'Huntsville', 'AL', '35805', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('74 Esch Junction', '81', 'Miami', 'FL', '33142', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('30 Dottie Alley', null, 'Amarillo', 'TX', '79182', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('39 Grasskamp Street', null, 'Charleston', 'WV', '25336', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('88357 Elgar Hill', null, 'Boulder', 'CO', '80310', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('916 Columbus Road', null, 'Colorado Springs', 'CO', '80935', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9150 Bay Point', '14', 'Sacramento', 'CA', '95828', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('44309 Crest Line Road', null, 'Montgomery', 'AL', '36114', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('96195 Randy Lane', '3', 'Tulsa', 'OK', '74116', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9 Hazelcrest Alley', null, 'Washington', 'DC', '20057', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('1 Service Avenue', null, 'Washington', 'DC', '20557', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('35 Anderson Circle', null, 'Denver', 'CO', '80291', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('365 Vidon Avenue', null, 'Silver Spring', 'MD', '20904', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6 Sutherland Circle', null, 'Arlington', 'VA', '22212', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('475 Schlimgen Point', null, 'Odessa', 'TX', '79769', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('297 Bunting Circle', '4', 'Hialeah', 'FL', '33018', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('729 Sunnyside Road', null, 'Washington', 'DC', '20414', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('4 Thackeray Street', '71', 'Atlanta', 'GA', '30358', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('313 Oxford Court', null, 'Shreveport', 'LA', '71137', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('71695 Elka Park', null, 'Boca Raton', 'FL', '33487', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('394 Vernon Hill', null, 'Round Rock', 'TX', '78682', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('1 Farragut Park', null, 'Little Rock', 'AR', '72215', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('1741 Browning Place', null, 'Detroit', 'MI', '48232', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('33 Cherokee Alley', null, 'Cincinnati', 'OH', '45264', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('5715 Onsgard Plaza', null, 'Mount Vernon', 'NY', '10557', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('92 Lukken Court', null, 'Ocala', 'FL', '34479', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('2008 Johnson Court', null, 'Buffalo', 'NY', '14215', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('7 Kingsford Drive', null, 'Arlington', 'VA', '22217', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('82 North Plaza', null, 'Winston Salem', 'NC', '27110', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('4987 Spohn Pass', null, 'San Diego', 'CA', '92105', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('757 Anderson Trail', null, 'Sioux Falls', 'SD', '57188', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('49526 Lillian Pass', null, 'Portland', 'OR', '97201', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('76 Twin Pines Street', null, 'San Antonio', 'TX', '78278', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6 Hanson Lane', null, 'Naples', 'FL', '34108', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('986 Portage Court', null, 'Houston', 'TX', '77293', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('51140 Cambridge Way', null, 'Santa Barbara', 'CA', '93150', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('52431 Comanche Lane', null, 'Los Angeles', 'CA', '90025', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('04619 Manitowish Crossing', null, 'Evansville', 'IN', '47712', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('447 Corben Way', null, 'Jersey City', 'NJ', '07305', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('3289 Village Hill', '40', 'Evansville', 'IN', '47732', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9 Del Sol Street', null, 'Seattle', 'WA', '98109', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('45 Holy Cross Alley', null, 'El Paso', 'TX', '88579', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('55710 Stone Corner Place', null, 'Lakeland', 'FL', '33805', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('576 Forest Run Parkway', null, 'Fort Wayne', 'IN', '46867', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('910 Straubel Avenue', '8', 'Lexington', 'KY', '40591', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('70 Claremont Plaza', '992', 'Charlotte', 'NC', '28220', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('401 Westport Street', null, 'Tulsa', 'OK', '74133', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9 Ryan Hill', null, 'Norwalk', 'CT', '06859', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('68 Longview Circle', null, 'Colorado Springs', 'CO', '80915', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('3 Sachs Drive', '03', 'San Francisco', 'CA', '94137', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('59 Bellgrove Terrace', null, 'Anchorage', 'AK', '99522', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('7 4th Way', null, 'Grand Rapids', 'MI', '49560', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('12 Bunting Center', '84', 'North Little Rock', 'AR', '72199', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('1378 Esch Street', null, 'Pompano Beach', 'FL', '33069', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('85069 6th Junction', null, 'Washington', 'DC', '20088', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('5 Pleasure Plaza', null, 'Virginia Beach', 'VA', '23459', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('81444 Stoughton Parkway', '4061', 'Tucson', 'AZ', '85705', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('620 Artisan Parkway', null, 'Chicago', 'IL', '60657', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('33000 Fallview Road', '68736', 'Des Moines', 'IA', '50305', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('626 Village Pass', null, 'Chicago', 'IL', '60614', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('129 Grim Street', null, 'Louisville', 'KY', '40287', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('416 Jenifer Pass', null, 'Las Vegas', 'NV', '89160', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('49 Anderson Pass', null, 'Garland', 'TX', '75044', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9 Esch Terrace', null, 'Louisville', 'KY', '40266', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('9100 Holmberg Hill', null, 'Shawnee Mission', 'KS', '66220', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('74748 Messerschmidt Center', null, 'Providence', 'RI', '02905', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('32 Acker Junction', '00317', 'Indianapolis', 'IN', '46207', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('82 Dawn Place', null, 'Brooksville', 'FL', '34605', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('31 Meadow Ridge Plaza', null, 'Montgomery', 'AL', '36109', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('82786 Rieder Center', null, 'Flint', 'MI', '48550', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('91502 Bobwhite Place', null, 'Dallas', 'TX', '75379', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('4991 Lien Junction', null, 'Louisville', 'KY', '40225', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('4363 Graceland Pass', null, 'Aiken', 'SC', '29805', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('2 Rusk Way', null, 'Boston', 'MA', '02124', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('05560 Hoard Lane', null, 'Houston', 'TX', '77271', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('34 Buena Vista Court', null, 'Seattle', 'WA', '98195', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('90 Dovetail Drive', null, 'El Paso', 'TX', '79994', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('89 Rieder Avenue', null, 'Shawnee Mission', 'KS', '66205', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('1696 Union Lane', null, 'Pueblo', 'CO', '81010', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('68831 Lerdahl Way', null, 'Naples', 'FL', '34108', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('7752 Ludington Crossing', null, 'Carson City', 'NV', '89706', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('42 Arapahoe Terrace', null, 'Charlotte', 'NC', '28299', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('5 Thackeray Point', '54621', 'Albany', 'NY', '12262', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('0 Dixon Plaza', null, 'Memphis', 'TN', '38136', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('30927 Commercial Crossing', null, 'Canton', 'OH', '44720', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('737 Rockefeller Pass', null, 'Boise', 'ID', '83705', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('524 Messerschmidt Parkway', null, 'Philadelphia', 'PA', '19131', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('0 Summer Ridge Place', null, 'Memphis', 'TN', '38104', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('90 Morning Alley', null, 'Saint Paul', 'MN', '55103', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('490 Pearson Terrace', '63', 'Washington', 'DC', '20535', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('72 Rusk Pass', null, 'Monroe', 'LA', '71213', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('03 East Point', null, 'Mobile', 'AL', '36641', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('01 Sugar Drive', null, 'Jacksonville', 'FL', '32209', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('00 Dixon Street', null, 'Honolulu', 'HI', '96815', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('40908 Carberry Center', '20447', 'Alexandria', 'LA', '71307', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('343 Hanson Pass', null, 'Saint Petersburg', 'FL', '33731', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('29 Hovde Lane', null, 'Saint Petersburg', 'FL', '33705', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('0623 Sutteridge Terrace', null, 'Peoria', 'IL', '61605', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('09266 Lakewood Hill', null, 'El Paso', 'TX', '88584', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('562 Dexter Avenue', null, 'Oakland', 'CA', '94605', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('518 Porter Plaza', null, 'Indianapolis', 'IN', '46278', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('7536 Chive Plaza', null, 'Denver', 'CO', '80262', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6 Express Street', null, 'Houston', 'TX', '77266', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('5345 Clyde Gallagher Place', null, 'Riverside', 'CA', '92505', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('20377 Norway Maple Alley', null, 'New York City', 'NY', '10184', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('47149 Washington Parkway', null, 'Houston', 'TX', '77223', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('89017 Westerfield Park', null, 'New York City', 'NY', '10014', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6 Farmco Parkway', null, 'Springfield', 'IL', '62764', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('1 Wayridge Crossing', '41871', 'Bethesda', 'MD', '20816', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6977 Prairieview Pass', null, 'Fort Myers', 'FL', '33906', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('64774 Sachtjen Way', null, 'San Antonio', 'TX', '78215', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('8064 Mcbride Park', null, 'Aurora', 'IL', '60505', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('1 Maryland Pass', null, 'Pensacola', 'FL', '32520', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('4643 Ridge Oak Hill', null, 'Abilene', 'TX', '79699', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('067 Shoshone Trail', null, 'Mobile', 'AL', '36605', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('90066 Amoth Hill', null, 'Dayton', 'OH', '45419', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('6153 Moland Trail', null, 'Dallas', 'TX', '75379', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('25 Eastwood Plaza', null, 'Beaverton', 'OR', '97075', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('365 Ryan Terrace', null, 'New York City', 'NY', '10280', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('51 Tomscot Center', null, 'Orlando', 'FL', '32859', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('51963 Arkansas Avenue', null, 'Visalia', 'CA', '93291', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('02 Rowland Lane', null, 'Boston', 'MA', '02119', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('50 Bashford Parkway', null, 'Jackson', 'MS', '39282', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('7655 Clemons Crossing', '004', 'Irvine', 'CA', '92710', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('54141 Hoepker Parkway', null, 'Los Angeles', 'CA', '90076', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('2 Arrowood Avenue', null, 'Young America', 'MN', '55564', 'US');
insert into `address` (`street1`, `street2`, `city`, `stateID`, `zipCode`, `countryID`) values ('31388 Namekagon Street', null, 'Melbourne', 'FL', '32941', 'US');